language: node_js
node_js:
  - "9"
sudo: true
dist: trusty

before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - npm install --save-dev @angular-devkit/core@0.0.26

script: 
  - ng test --watch false --single-run
  - ng e2e
  - ng build -prod
  - sed -i -e 's#<base href="/">#<base href="http://www.curlify.net.s3-website.eu-west-2.amazonaws.com/">#g' ./dist/index.html 
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_CODE
  bucket: "www.curlify.net"
  region: "eu-west-2"
  acl: public_read
  cache_control: "max-age=2592000,public"
  expires: "2034-01-01T00:00:00Z"
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master 